export enum Sex {
  M = "M",
  F = "F"
}

export enum BethesdaLevel {
  CLASS2 = "CLASS2",
  CLASS3 = "CLASS3",
  CLASS4 = "CLASS4",
  CLASS5 = "CLASS5",
  CLASS6 = "CLASS6"
}

export enum NoduleSize {
  LESS_THAN_ONE = "LESS_THAN_ONE",
  BETWEEN_ONE_AND_TWO = "BETWEEN_ONE_AND_TWO",
  MORE_THAN_TWO = "MORE_THAN_TWO"
}

export enum NoduleShape {
  OVAL = "OVAL",
  ROUND = "ROUND",
  VERTICAL = "VERTICAL",
  IRREGULAR = "IRREGULAR"
}

export enum NoduleContours {
  CLEAR_EVEN = "CLEAR_EVEN",
  CLEAR_UNEVEN = "CLEAR_UNEVEN",
  FUZZY_EVEN = "FUZZY_EVEN",
  FUZZY_UNEVEN = "FUZZY_UNEVEN"
}

export enum NoduleEchogenicity {
  HYPOECHOIC = "HYPOECHOIC",
  ISOECHOIC = "ISOECHOIC"
}

export enum NoduleVascularization {
  CENTRAL = "CENTRAL",
  PERIPHERAL = "PERIPHERAL",
  MIXED = "MIXED"
}

export enum NoduleElastography {
  TYPE2 = "TYPE2",
  TYPE3 = "TYPE3",
  TYPE4 = "TYPE4"
}

export enum Thirads {
  CLASS2 = "CLASS2",
  CLASS3 = "CLASS3",
  CLASS4 = "CLASS4"
}

export enum NoduleStructure {
  HOMOGENEOUS = "HOMOGENEOUS",
  HETEROGENEOUS = "HETEROGENEOUS",
  SPONGY = "SPONGY",
  INHOMOGENEOUS_DUE_TO_CENTRAL_CYSTS = "INHOMOGENEOUS_DUE_TO_CENTRAL_CYSTS",
  INHOMOGENEOUS_DUE_TO_PERIPHERAL_CYSTS = "INHOMOGENEOUS_DUE_TO_PERIPHERAL_CYSTS",
  MACROCALCINATES = "MACROCALCINATES",
  MICROCALCINATES = "MICROCALCINATES"
}
