spring:
  application:
    name: ThyroidNoduleDMS

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

  datasource:
    url: 'jdbc:h2:mem:esignature;DB_CLOSE_DELAY=-1;'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cors-mapping:
  endpoints:
    - endpoint-pattern: "/**"
      allowed-methods:
        - "GET"
        - "POST"
        - "HEAD"
        - "OPTIONS"
        - "PUT"
        - "DELETE"
      allowed-origins: "http://localhost:4200"
      allowed-credentials: false

jwt:
  secret: 3bB-AxG9iZC8gb0K2iwpYLy2woirjk8_kiCRQ_xVMVi1l5LqX2bSINoXZi4zbKfNhT1VbqWMD2KQ0BFzW2ZqmA
  validity: 360000000

