spring:
  datasource:
    url: 'jdbc:h2:mem:esignature;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
